### ISSUE TITLE
``Loading the data into PostgreSQL``  failed

### ISSUE THREAD

**Issue by uptonking** [dylburger/noaa-ghcn-weather-data#1]
exec  `pip install -r requirements.txt` error
```
Invalid requirement: 'version https://git-lfs.github.com/spec/v1'
It looks like a path. Does it exist ?
```
 I find ` https://git-lfs.github.com/spec/v1` does not exist.
The Jupyter code helped me ceate table `weather_data` in PostgreSQL weather db, but didn't ingest data in 2015.csv.

**Comment by dylburger** [comment]
@uptonking I was previously using [Git LFS](https://git-lfs.github.com/) to store some of the larger files in the repo, but I'd stopped using it after hitting Github space limits for LFS. The `requirements.txt` file was also stored using Git LFS and that seems to have caused some issues here.

I've removed LFS support completely. Can you see if that fixes the first issue?

The second issue - failing to ingest data from the `2015.csv` file - seems to be different. Can you tell me the specific error message you're seeing there?

Did you run this code to download the CSV file from the NOAA FTP server?

    curl -O ftp://ftp.ncdc.noaa.gov/pub/data/ghcn/daily/by_year/2015.csv.gz

**Comment by uptonking** [comment]
@dylburger thanks. please close the issue.
The 2015.csv was ingested after my waiting of 15min.

**Comment by dylburger** [comment]
@uptonking thanks. This dataset is a bit large - something smaller might be better so users can get working quickly.

**Comment by savan8192** [comment]
Hi, I am trying to ingest the data, I don't mind waiting 15 mins but but kernel dies in the process. I reduced the chunk size but that's not helping either - kernel still dies. Any advice help will be gracefully received, thank you. 

![image](https://user-images.githubusercontent.com/1427394/55074593-98275680-5088-11e9-85b5-e94e43cfe65b.png)

**Comment by savan8192** [comment]
I got around this issue by manually removing the entries from 2015.csv and things worked fine.
