### ISSUE TITLE
Cannot download data from FTP uri

### ISSUE THREAD

**Issue by xjr7670** [dylburger/noaa-ghcn-weather-data#5]
I got this:

![image](https://user-images.githubusercontent.com/7731794/62374622-f3a1ad80-b56e-11e9-9269-a49e74af4f4a.png)

 does it have other download link?

**Comment by dylburger** [comment]
Hi @xjr7670 , would you mind checking again? I'm able to hit that FTP server now.

If you still can't, here are a few things you might try:

* Make sure that host (or the FTP protocol) isn't being blocked by a firewall, or by some other program on your local machine. You can use a tool like `nc` or `telnet` to confirm that you can talk to that host on port 21 (FTP), for example:

```bash
$ nc -w 3 -z ftp.ncdc.noaa.gov 21
Connection to ftp.ncdc.noaa.gov port 21 [tcp/ftp] succeeded!
```

* You can take a look at the [NOAA datasets page](https://www.ncdc.noaa.gov/data-access/quick-links#ghcn) to see if there's another method to get the data.

Let me know if that helps or if you have any other questions.

**Comment by xjr7670** [comment]
Thank you @dylburger for your reply.

It may cause by the special network at my location. I have tried in different network and downloaded it finally. Although it's a very very slow network connection🤣
